### ISSUE TITLE
No UDP Connections with Electron

### ISSUE THREAD

**Issue by jch9678** [whphhg/vcash-electron#24]
With electron I don't have any UDP connections, I noticed the same behavior in your screenshots as well.  The original wallet has UDP connections.

**Comment by whphhg** [comment]
The screenshots are from testnet where there were 0 UDP connections at the time I took the screenshot. On mainnet you will see the UDP connection count unless you've disabled `udp` in your `~/Vcash/config.dat`. 

Make sure `enable` under `udp` is set to `1` like below,

    "network":
    {
        "udp":
        {
            "enable": "1"
        }
    },

The setting is nearly at the top of the file on line 15 and remember to close the wallet before making the change.

**Comment by jch9678** [comment]
UDP is enabled in the config.  I get UDP connections when I use the original wallet, just not the electron version.  They use the same config right?

**Comment by whphhg** [comment]
Yes, the daemon config is the same whether you use Electron GUI, wxWidgetsGUI or only the daemon itself. They all get their information from the same place, the daemon, so if one shows the UDP count, others will as well.

**Comment by jch9678** [comment]
Starting the Electron GUI alone, there are not UDP connections
![electron](https://user-images.githubusercontent.com/12422346/27487250-ce570b86-57f8-11e7-9cdb-137f3874e318.PNG)

When I start wxWidgetsGUI while Electron is running, they report different numbers and stay that way.
![both](https://user-images.githubusercontent.com/12422346/27487318-008edf66-57f9-11e7-8075-3e1e7a580f1f.PNG)

If I start the wxWidgets first and then the Electron GUI, they both report the same connections TCP and UDP more or less.  Then if I close wxWidgets the Electron connection drops, reconnects with 0 UDP.

I used the installer for the Electron GUI, could they be using different daemons?  Maybe when electron starts up while wxwidgets is already running it connects to that daemon, but when wxwidgets is closed, it's daemon closes, electron loses connection and starts up it's own daemon.  Could the installer be the problem?

**Comment by whphhg** [comment]
You're describing the problem really well, however the installer you've used is using the same 0.6.0.4 daemon as the wxWidgetsGUI is so it shouldn't be a problem. It's not recommended to start multiple daemons on Windows as it will cause unintended behaviour (as you described) due to this issue https://github.com/openvcash/vcash/issues/18.

I'm going to take a long shot here, but I think the issue is that you are expecting to see connection counts update as fast as they do in wxWidgetsGUI, which would require the Electron GUI to make RPC requests to update the info every few seconds, where wxWidgetsGUI if I'm not mistaken reacts to the changes in the stack without the need to constantly pool for new info.

To see if the above is the case:
1. make sure there are no previous Vcash / Electron processes running
2. start and let the Electron GUI run for a little more than a minute after the transactions view loads and you should see UDP count update

While you're waiting you can press `alt + c` and type in `getnetworkinfo` which will return TCP and UDP counts so you can see what the GUI is going to show once that minute is up and it pools for new info.

The approach taken in the Electron GUI is to update network info every 3s until there are at least 3 TCP connections, after that update every minute. So it is entierly possible that the UDP count could be at 0 for around a minute before it's updated.

**Comment by jch9678** [comment]
Yeah I was only running multiple daemons to test.  

Actually I've already done those instructions when I was testing and let Electron run overnight.  Still no luck.

I just tested on another computer and it worked fine, so it's just on this system.

Now I just downloaded the standalone, instead of the installer, and it worked fine.  I have UDP connections.

Now I'm leaning towards Avast messing with the installer when it installed.

**Comment by jch9678** [comment]
So I just downloaded the standalone on the computer that was messed up, started that up and it worked.

Closed the standalone and started the installer version and it worked.  Very weird.  I'm thinking Avast Behavior messed with something on the original install or UDP was somehow firewalled, I really don't know but it's working.
